---
title: "Building an interactive graph for data on holocaust survivors and victims, and a discussion on Bouie's themes"
author: 
  - Krishiv
thanks: "Code and data are available at: https://github.com/Krishiv-J/Mini-Essay-12. Shiny Applicaiton available at: https://htcivf-krishiv-jain.shinyapps.io/Mini-Essay-12/"
date: today
date-format: long
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
```


# Introduction

The Holocaust stands as one of the darkest chapters in human history, marked by unspeakable atrocities committed against millions of innocent lives. Among the numerous concentration camps where these atrocities occurred, Auschwitz is one of the most well known as it had the most number of deaths. An interactive bar chart and table was created to represent this data, specifically, on the residence based on the person's religions. 

For the creation of the interactive chart and table, R [@citeR] was used, along with the following packages: tidyverse [@citetidyverse], shiny [@citeshiny], ggplot2 [@citeggplot2], DT [@citeDT]. Moreover, @citetextbook as well as @citeUNC was used to write the code to create the Shiny application. 

The interactive graph features a bar chart where the y-axis represents the different residences of the victims, and the x-axis displays the total number of deaths. Users can select specific religions or opt for all religions to generate the visualization. Notably, the chart is limited to displaying data for the top 20 residences. Whilst the graph provides a high-level overview of victim demographics, the accompanying interactive table offers more detailed insights. In the table, users can access individual victim records, including their first and last names, along with additional information such as date of birth and date of death.  

# Data {#sec-data}

The data set used  comprises partially preserved Death Books (Sterbebücher) from the Auschwitz Concentration Camp. It documents the deaths of prisoners registered in the camp between July 29, 1941, and December 31, 1943. These records consist of 46 volumes, providing information on the individuals' last name, first name, date of birth, date of death, birthplace, residence, and religion. The events recorded in the data set occurred between July 29, 1941, and December 31, 1943. The data set contains records for a total of 65,280 individuals who died at Auschwitz Concentration Camp.


# Discussion

Bouie's exploration of historical data on slavery provides valuable insights that resonate with our analysis of Holocaust victim demographics at Auschwitz. One theme that stands out is the balance between abstraction and humanisation that is often inherent in data analysis. Bouie discusses about how the act of quantifying human suffering through numerical representations can risk reducing individuals to mere data points, and devoid of their humanity. This tension is visible in our interactive graph, where victims are depicted as statistical counts, obscuring the richness of their individual stories.

Moreover, for the purpose of this analysis, only the top 20 residences of the victims have been included in the interactive visualization. This selective approach may obscure the diverse origins of the individuals who lost their lives in Auschwitz. This limitation raises important questions about representation and the potential for overlooking significant demographic patterns within the data set. This decision to focus on the top 20 residences reflects a broader theme discussed by Bouie regarding the challenges of adequately representing historical data and the inherent biases introduced by selective analysis.

However, our analysis also underscores the power of technology to humanise historical narratives. By providing users with access to individual victim records in the interactive table, we go beyond the limitations of quantitative abstraction and invite deeper engagement with the human stories behind the data. Each name in the table represents a life lost, a family shattered, and a story untold.

Moreover, Bouie's examination of the role of technology in shaping public engagement with historical data resonates deeply with our approach. In leveraging interactive visualisation tools, we bridge the gap between historical scholarship and public awareness, and invite users to actively engage with Holocaust history. Through intuitive interfaces and accessible data presentation, we allow individuals to explore victim demographics and confront the sobering realities of the Holocaust. In doing so, we honor the memory of those who perished while fostering a collective commitment to remembrance and education.

# Conclusion

In conclusion, our interactive analysis offers valuable insights into the ethnic origins and number of Holocaust victims at Auschwitz. Through the juxtaposition of quantitative data and individual victim records, we aim to honour the memory of those who died and allow the public to more easily access data related to the Holocaust.

\newpage

# References


